[tox]
envlist= py38, py39, py310, py311
[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311
    
[testenv]
deps= -rRequirment_dev.txt
commands= 
    flake8 src --count --select=E9,F63,F7,E82 --show-source --statistics
    flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    mypy src/
    pytest -v tests/unit
    pytest -v tests/integration